name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Extract version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -c 2-)"

      - name: Create release
        uses: actions/create-release@v1
        #
        #with:
         # tag_name: ${{ env.VERSION }}
          #release_name: Release ${{ env.VERSION }}
          #body: |
           # Release ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: | 
            Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: . 
          asset_name: ${{ env.VERSION }}
          asset_content_type: application/zip
